import { InventoryItem } from '../types/item'

export const seedItems: InventoryItem[] = [
  {
    id: 'magic_wand',
    sku: 'SKU-WAND-001',
    title: 'Жезл',
    image: '/assets/icons/magic_witch_weapon_stick_game_play_war_wizard_icon_262411.png',
    weight: 2,
    qty: 1,
  },
  {
    id: 'sword',
    sku: 'SKU-SWORD-001',
    title: 'Меч',
    image: '/assets/icons/battle_game_sword_fight_weapon_gift_token_war_power_icon_262404.png',
    weight: 3,
    qty: 2,
  },
  {
    id: 'crown',
    sku: 'SKU-CROWN-001',
    title: 'Корона',
    image: '/assets/icons/crown_game_sports_console_controller_sport_video_play_gaming_icon_262443.png',
    weight: 1,
    qty: 1,
  },
  {
    id: 'pistol',
    sku: 'SKU-PISTOL-001',
    title: 'Пистолет',
    image: '/assets/icons/game_army_pistol_sword_war_military_gift_weapon_gun_icon_262418.png',
    weight: 2.5,
    qty: 1,
  },
  {
    id: 'mana_potion',
    sku: 'SKU-POTION-001',
    title: 'Зелье маны',
    image: '/assets/icons/game_drop_water_jar_bottle_drink_liquid_blue_toxic_icon_262448.png',
    weight: 0.5,
    qty: 3,
  },
  {
    id: 'money_bag',
    sku: 'SKU-MONEY-001',
    title: 'Мешок золота',
    image: '/assets/icons/game_coin_cash_sack_dollar_bag_bucket_buck_money_icon_262454.png',
    weight: 5,
    qty: 1,
  },
  {
    id: 'gold_coins',
    sku: 'SKU-COINS-001',
    title: 'Бочка монет',
    image: '/assets/icons/award_rich_coin_medal_bucket_bunch_gold_game_icon_262432.png',
    weight: 10,
    qty: 1,
  },
  {
    id: 'castle',
    sku: 'SKU-CASTLE-001',
    title: 'Замок',
    image: '/assets/icons/castle_tower_house_queen_game_king_building_princess_prince_icon_262429.png',
    weight: 50,
    qty: 1,
  },
  {
    id: 'war_hammer',
    sku: 'SKU-HAMMER-001',
    title: 'Боевой молот',
    image: '/assets/icons/game_battle_hammer_stone_breach_weapon_equipment_nordic_ar_icon_262427.png',
    weight: 7,
    qty: 1,
  },
]
